name: Terraform Plan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: "1.0.0"

    - name: Terraform Initialize
      run: terraform init

    - name: Terraform Plan
      run: terraform plan

     - name: Terraform Format
       run: terraform fmt -check
     - name: Terraform Validate
       run: terraform validate
